<?php
/**
 * Created by PhpStorm.
 * User: manus
 * Date: 2018-12-27
 * Time: 16:53
 */

class PagoRecurrente extends \GLFramework\Model
{
    public static $TIPO_PAGO_RECURRENTE_OFF = 0;
    public static $TIPO_PAGO_RECURRENTE_ANUAL = 1;
    public static $TIPO_PAGO_RECURRENTE_MENSUAL = 2;
    public static $TIPO_PAGO_RECURRENTE_SEMANAL = 3;
    public static $TIPO_PAGO_RECURRENTE_DIARIO = 4;

    protected $table_name = 'pagos_recurrentes';

    public $id;
    public $concepto;
    public $cantidad;
    public $tipo;
    public $primer_dia;
    public $generar_pagado;
    public $forma_pago;
    public $desactivar;

    private $pprCache = false;

    protected $definition = array(
        'index' => 'id',
        'fields' => array(
            'nombre' => "varchar(255)",
            'concepto' => "varchar(255)",
            'cantidad' => "double(10, 2)",
            'tipo' => "int(11)",
            'primer_dia' => "int(11)",
            'generar_pagado' => "int(11)",
            'forma_pago' => "varchar(2000)",
            'desactivar' => "int(1)",
        )
    );

    public function getTiposPago() {
        return [
            '0' => 'Off',
            '1' => 'Anual',
            '2' => 'Mensual',
            '3' => 'Semanal',
            '4' => 'Diario',
        ];
    }

    public function save($updateIndex = false)
    {
        $this->pprCache = false;
        return parent::save($updateIndex); // TODO: Change the autogenerated stub
    }

    /**
     * @return bool|\GLFramework\ModelResult|PersonaPagoRecurrente[]
     * @throws Exception
     */
    public function getPersonasPagoRecurrente() {
        if(!$this->pprCache) {
            $ppr = new PersonaPagoRecurrente();
            $this->pprCache = $ppr->get(['pago_recurrente_id' => $this->id ]);
        }
        return $this->pprCache;
    }


    public function isPersona($id) {
        $personas = $this->getPersonasPagoRecurrente();
        foreach ($personas as $item) {
            if($item->persona_id == $id) return true;
        }
        return false;
    }

    public function generarConcepto($time = false) {
        if(!$time) {
            $time = time();
        }
        if($this->tipo == PagoRecurrente::$TIPO_PAGO_RECURRENTE_ANUAL) {
            return $this->concepto . " - " . date("Y", $time);
        }
        if($this->tipo == PagoRecurrente::$TIPO_PAGO_RECURRENTE_MENSUAL) {
            $meses = ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"];

            return $this->concepto . " - " . strtoupper($meses[date("m", $time)-1]);
        }
        if($this->tipo == PagoRecurrente::$TIPO_PAGO_RECURRENTE_SEMANAL) {
            return $this->concepto . " - Sem. " . date("W - Y", $time);
        }
        if($this->tipo == PagoRecurrente::$TIPO_PAGO_RECURRENTE_DIARIO) {
            return $this->concepto . " - " . date("d/m/Y", $time);
        }
        return $this->concepto;
    }
}