<?php
/**
 * Created by PhpStorm.
 * User: manus
 * Date: 2018-12-27
 * Time: 16:30
 */

namespace GLApp\personas;


use GLFramework\Controller\AuthController;

class edit extends AuthController
{

    public $persona;
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $this->persona = new \Persona($_GET['id']);
        if(isset($_POST['save'])) {
            $this->persona->setData($_POST['persona']);
            $this->persona->save(true);
            if($_GET['id'] == 'add') {
                $this->quit("?id=" . $this->persona->id);
            }
        }
    }
}