<?php
/**
 * Created by PhpStorm.
 * User: manus
 * Date: 2018-12-27
 * Time: 16:30
 */

namespace GLApp\personas;


use GLFramework\Controller\AuthController;

class home extends AuthController
{
    public $personas;
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $this->personas = new \Persona();
        $this->personas = $this->personas->get_all();
    }


}