<?php
/**
 * Created by PhpStorm.
 * User: manus
 * Date: 2018-12-27
 * Time: 16:13
 */

namespace GLApp\pagos;


use GLFramework\Controller\AuthController;

class edit extends AuthController
{
    public $pago;
    public $personas;
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $this->pago = new \Pago($_GET['id']);
        $this->personas = new \Persona();
        $this->personas = $this->personas->get_all();
        if(isset($_POST['save'])) {
            $this->pago->setData($_POST['pago']);
            if($this->pago->pagado && !$this->pago->fecha_abono) {
                $this->pago->fecha_abono = today();
            }
            $this->pago->save(true);

            if($_GET['id'] == 'add') {
                $this->quit("?id=" . $this->pago->id);
            }
        }

        if(isset($_POST['delete'])) {
            $this->pago->delete();
            $this->addMessage("Se ha eliminado correctamente");
            $this->quit("../");
        }
    }


}