<?php
/**
 * Created by PhpStorm.
 * User: manus
 * Date: 2018-12-27
 * Time: 16:09
 */

namespace GLApp\pagos;


use GLFramework\Controller\AuthController;

class home extends AuthController
{

    public $pagos;

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $this->pagos = new \Pago();
        $this->pagos = $this->pagos->get_all();
    }


}