<?php
/**
 * Created by PhpStorm.
 * User: manus
 * Date: 2018-12-27
 * Time: 16:09
 */

namespace GLApp\recurrentes;


use GLFramework\Controller\AuthController;

class home extends AuthController
{

    public $recurrentes;

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $this->recurrentes = new \PagoRecurrente();
        $this->recurrentes = $this->recurrentes->get_all();
    }


}